name: Bot TikTok 1 - Pro

on:
  schedule:
    - cron: '10 10,16,19 * * *' 
  workflow_dispatch:      # 👈 C'est ici qu'on ajoute l'option du bouton
    inputs:
      force_post:
        description: 'Forcer la publication immédiate ?'
        type: boolean
        default: false

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 📥 Récupération du code
        uses: actions/checkout@v4

      - name: 🐍 Installation de Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 📦 Installation des dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 🌐 Installation forcée du moteur Playwright
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2t64
          playwright install chromium

      - name: 🚀 Lancement du Bot TikTok
        env:
          ACCOUNT_NAME: "tiktok_1"
          # 👈 On récupère la valeur du bouton coché ici :
          FORCE_POST: ${{ github.event.inputs.force_post == 'true' && '1' || '0' }}
          
          DRIVE_FOLDER_ID: ${{ secrets.DRIVE_FOLDER_ID }}
          TIKTOK_COOKIES_TIKTOK_1: ${{ secrets.TIKTOK_COOKIES_TIKTOK_1 }}
          GDRIVE_SA_JSON_B64: ${{ secrets.GDRIVE_SA_JSON_B64 }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python src/main.py

      - name: Upload Screenshot on Failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: tiktok-error-screenshot
          path: debug_tiktok_error.png